apiVersion: v1
kind: Secret
metadata:
  name: job-scraper-secret
type: Opaque
stringData:
  MONGO_URI: "mongodb+srv://<user>:<pass>@<cluster>.mongodb.net/?retryWrites=true&w=majority"
  DISCORD_WEBHOOK_URL: "https://discord.com/api/webhooks/<id>/<token>"
